const niceClasses = [
    { "id": 1, "description": "Produtos químicos para indústria, ciência, fotografia." },
    { "id": 2, "description": "Tintas, vernizes, lacas; conservantes contra ferrugem." },
    { "id": 3, "description": "Preparações para branquear e outras substâncias para lavanderia." },
    { "id": 4, "description": "Óleos e graxas industriais; lubrificantes." },
    { "id": 5, "description": "Preparações farmacêuticas e veterinárias." },
    { "id": 6, "description": "Metais comuns e suas ligas." },
    { "id": 7, "description": "Máquinas e máquinas-ferramentas." },
    { "id": 8, "description": "Ferramentas e instrumentos manuais." },
    { "id": 9, "description": "Aparelhos e instrumentos científicos, de pesquisa, navegação." },
    { "id": 10, "description": "Aparelhos e instrumentos cirúrgicos, médicos, odontológicos." },
    { "id": 11, "description": "Aparelhos e instalações para iluminação, aquecimento, etc." },
    { "id": 12, "description": "Veículos; aparelhos para locomoção por terra, ar ou água." },
    { "id": 13, "description": "Armas de fogo; munições e projéteis." },
    { "id": 14, "description": "Metais preciosos e suas ligas." },
    { "id": 15, "description": "Instrumentos musicais." },
    { "id": 16, "description": "Papel e papelão; material de escritório." },
    { "id": 17, "description": "Borracha, guta-percha, goma, amianto, mica." },
    { "id": 18, "description": "Couro e imitações de couro." },
    { "id": 19, "description": "Materiais de construção não metálicos." },
    { "id": 20, "description": "Móveis, espelhos, molduras." },
    { "id": 21, "description": "Utensílios e recipientes para casa e cozinha." },
    { "id": 22, "description": "Cordas e barbantes; redes; tendas e lonas." },
    { "id": 23, "description": "Fios para uso têxtil." },
    { "id": 24, "description": "Têxteis e substitutos para têxteis." },
    { "id": 25, "description": "Vestuário, calçados e chapelaria." },
    { "id": 26, "description": "Rendas e bordados, fitas e laços." },
    { "id": 27, "description": "Carpetes, tapetes, capachos e esteiras." },
    { "id": 28, "description": "Jogos e brinquedos; artigos para ginástica e esporte." },
    { "id": 29, "description": "Carne, peixe, aves e caça." },
    { "id": 30, "description": "Café, chá, cacau e café artificial." },
    { "id": 31, "description": "Produtos agrícolas, hortícolas e florestais frescos." },
    { "id": 32, "description": "Cervejas; águas minerais e gasosas." },
    { "id": 33, "description": "Bebidas alcoólicas (exceto cervejas)." },
    { "id": 34, "description": "Tabaco e artigos para fumantes." },
    { "id": 35, "description": "Publicidade; gestão de negócios comerciais." },
    { "id": 36, "description": "Seguros; negócios financeiros; negócios monetários." },
    { "id": 37, "description": "Construção civil; reparos; serviços de instalação." },
    { "id": 38, "description": "Telecomunicações." },
    { "id": 39, "description": "Transporte; embalagem e armazenagem de produtos." },
    { "id": 40, "description": "Tratamento de materiais." },
    { "id": 41, "description": "Educação; provimento de treinamento; entretenimento." },
    { "id": 42, "description": "Serviços científicos e tecnológicos." },
    { "id": 43, "description": "Serviços de fornecimento de comida e bebida." },
    { "id": 44, "description": "Serviços médicos; serviços veterinários." },
    { "id": 45, "description": "Serviços jurídicos; serviços de segurança." }
];